openapi: 3.0.3
info:
  title: Fastify todo api
  description: Fastify todo api Swagger
  version: 1.0.0
components:
  schemas:
    user:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    todo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        describe:
          type: string
        userId:
          type: string
        user:
          $ref: "#/components/schemas/user"
paths:
  /sign_up:
    post:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
  /hello/:
    get:
      summary: sample api
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /todo/:
    get:
      tags:
        - todo
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/todo"
    post:
      tags:
        - todo
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/todo"
servers:
  - url: localhost:8080
