openapi: 3.0.3
info:
  title: Fastify todo api
  description: Fastify todo api Swagger
  version: 1.0.0
components:
  schemas:
    def-0:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      title: user
    def-1:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        describe:
          type: string
        userId:
          type: string
        user:
          $ref: "#/components/schemas/def-0"
      title: todo
paths:
  /hello:
    get:
      summary: sample api
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: string
  /todo:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/def-1"
    post:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/def-1"
  /sign_up:
    post:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
servers:
  - url: localhost:8080
